/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("temp.kotlin-library-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text:${ProjectVersions.commonsText}")
}

dependencies {
    api(project(":list"))
}
