name: "Noop test"
on:
  push:
    branches: [ "main", "renovate/*" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "hi"
